// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lwhrtzlpxgpmozrcxtrw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx3aHJ0emxweGdwbW96cmN4dHJ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0ODE0MTQsImV4cCI6MjA3MzA1NzQxNH0.dCprkffclhZ7892xY5STYfK1oJrrvnqMLHtNh_YzyDU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});